pipeline:
  identifier: Build_james_crowley_ci_benchmark_1_1719248079016
  name: Build ci-benchmark-1
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1719248019120
        repoName: james-crowley/ci-benchmark-1
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: build_image
                  identifier: build_image
                  spec:
                    shell: Sh
                    command: docker build -f Dockerfile -t demo:test .
                  description: Builds Docker Image
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
        description: ""
