pipeline:
  identifier: Build_james_crowley_ci_benchmark_1_1719248079016
  name: Build ci-benchmark-1
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1719248019120
        repoName: james-crowley/ci-benchmark-1
  stages:
    - parallel:
        - stage:
            identifier: build
            name: build
            spec:
              caching:
                enabled: false
                paths: []
              cloneCodebase: true
              execution:
                steps:
                  - step:
                      type: Run
                      name: build_image
                      identifier: build_image
                      spec:
                        shell: Sh
                        command: docker build -f Dockerfiled -t demo:test .
                      description: Builds Docker Image
              platform:
                os: Linux
                arch: Amd64
              runtime:
                type: Cloud
                spec: {}
            type: CI
            description: ""
        - stage:
            name: testing
            identifier: testing
            description: ""
            type: CI
            spec:
              cloneCodebase: true
              platform:
                os: Linux
                arch: Arm64
              runtime:
                type: Cloud
                spec: {}
              execution:
                steps:
                  - step:
                      type: Run
                      name: Run_1
                      identifier: Run_1
                      spec:
                        shell: Sh
                        command: echo "hello world"
    - stage:
        name: finish
        identifier: finish
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: sleep 10
